bugtracker2/bugtracker2/urls.py
from django.contrib import admin
from django.urls import path
from . import views as vbase
from django.conf.urls import include
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('', auth_views.LoginView.as_view(template_name='accounts/login.html'),name='login'),
    path('home/',vbase.HomePage.as_view(), name='home'),
    path('accounts/', include('accounts.urls',namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('test/', vbase.TestPage.as_view(), name='test'),
    path('thanks/', vbase.ThanksPage.as_view(), name='thanks'),
    path('admin/', admin.site.urls),
    path('tickets/', include('tickets.urls',namespace='tickets')),
    path('projects/', include('projects.urls',namespace='projects')),
]

bugtracker2/tickets/urls.py
from django.urls import path
from . import views

app_name = 'tickets'

urlpatterns = [
    path('',views.TicketList.as_view(),name='all'),
    path('new/',views.CreateTicket.as_view(),name='create'),
    path('by/<username>/',views.UserTickets.as_view(),name='for_user'),
    path('by/<username>/<pk>/',views.TicketDetail.as_view(),name='single'),
    path('delete/<pk>/',views.DeleteTicket.as_view(),name='delete'),
]

bugtracker2/tickets/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings
import misaka
from projects.models import Project
# Create your models here.
from django.contrib.auth import get_user_model
User = get_user_model()

class Ticket(models.Model):
    user = models.ForeignKey(User,related_name='tickets', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now=True)
    message = models.TextField()
    message_html = models.TextField(editable=False)
    project = models.ForeignKey(Project, related_name='tickets', null=True, blank=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.message

    def save(self,*args,**kwargs):
        self.message_html = misaka.html(self.message)
        super().save(*args,**kwargs)

    def get_absolute_url(self):
        return reverse('tickets:single',kwargs={'username':self.user.username,'pk':self.pk})

    class Meta:
        ordering = ['-created_at']
        unique_together = ['user','message']

bugtracker2/tickets/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.urls import reverse, reverse_lazy
from django.http import Http404
from django.views import generic
from braces.views import SelectRelatedMixin
# Create your views here.
from . import models
from . import forms
from django.contrib.auth import get_user_model
from django.contrib import messages
from django.http import HttpResponse, HttpResponseRedirect

User = get_user_model()

class TicketList(SelectRelatedMixin,generic.ListView):
    model = models.Ticket
    select_related = ('user', 'project')

class UserTickets(generic.ListView):
    model = models.Ticket
    template_name = 'tickets/user_ticket_list.html'

    def get_queryset(self):
        try:
            self.ticket_user = User.objects.prefetch_related('tickets').get(username__iexact=self.kwargs.get('username'))
        except User.DoesNotExist:
            raise Http404
        else:
            return self.ticket_user.tickets.all()

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context['ticket_user'] = self.ticket_user
        return context

class TicketDetail(SelectRelatedMixin,generic.DetailView):
    model = models.Ticket
    select_related = ('user','project')

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user__username__iexact=self.kwargs.get('username'))

class CreateTicket(LoginRequiredMixin,SelectRelatedMixin,generic.CreateView):
    fields = ('message', 'project')
    model = models.Ticket

    def form_valid(self,form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)

class DeleteTicket(UserPassesTestMixin, LoginRequiredMixin, SelectRelatedMixin, generic.DeleteView):
    model = models.Ticket
    select_related = ('user','project')
    success_url = reverse_lazy('tickets:all')

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user_id = self.request.user.id)

    def delete(self,*args,**kwargs):
        messages.success(self.request,'Ticket Deleted')
        return super().delete(*args,**kwargs)

    def test_func(self):
        return self.request.user.is_staff

    def handle_no_permission(self):
        messages.add_message(self.request, messages.INFO, 'Not enough permissions to delete a ticket')
        return HttpResponseRedirect(self.request.META.get('HTTP_REFERER'))

bugtracker2/tickets/templates/tickets/_ticket.html
<div class="ticket container">
	<p>{{ ticket.message_html|safe }}</p>
		<p>
			<span class="username"><a href="{% url 'tickets:for_user' username=ticket.user.username %}">@{{ ticket.user.username }}</a></span>
			<time class="time">{{ ticket.created_at }}</time>
			{% if ticket.project %}
			<span class="project-name">in <a href="{% url 'projects:single' slug=ticket.project.slug %}">{{ ticket.project.name }}</a></span>
			{% endif %}
		</p>

			{% if user.is_authenticated and ticket.user == user and not hide_delete %}
				<a href="{% url 'tickets:delete' pk=ticket.pk %}" title="delete" class="btn btn-simple">
					<span class="glyphicon glyphicon-remove text-danger" aria-hidden="true"></span>
					<span class="text-danger icon-label">Delete</span>
				</a>
			{% endif %}
</div>

bugtracker2/tickets/templates/tickets/ticket_base.html
{% extends "base.html" %}

{% block content %}
<div class="tickets-page">
  <div class="container">
    <div class="row">
      {% block preticket %}{% endblock %}
      {% block ticket_content %}{% endblock %}
      {% block ticketticket %}{% endblock %}

    </div>

  </div>

</div>

{% endblock %}

bugtracker2/tickets/templates/tickets/ticket_confirm_delete.html
{% extends "tickets/ticket_base.html" %}

{% block ticket_content %}
<h3>Are you sure you want to delete this ticket?</h3>

<div class="tickets">
{% include "tickets/_ticket.html" with ticket=object hide_delete=True %}
</div>

<form method="POST">
  {% csrf_token %}
  <input type="submit" name="" value="Confirm Delete" class='btn btn-danger btn-large'>
    <a class='btn btn-simple btn-large btn-default' href="{% url 'tickets:single' username=user.username pk=object.pk %}">Cancel</a>

</form>

{% endblock %}

bugtracker2/tickets/templates/tickets/ticket_detail.html
{% extends "tickets/ticket_base.html" %}

{% block ticket_content %}
{% if messages %}
    {% for message in messages %}
    <p{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p>
    {% endfor %}
{% endif %}
  <div class="col-md-8">
    {% include "tickets/_ticket.html" %}
  </div>
{% endblock %}

bugtracker2/tickets/templates/tickets/ticket_form.html
{% extends "tickets/ticket_base.html" %}
{% load bootstrap3 %}

{% block ticket_content %}
<div class="container">
    <h4>Create a new ticket</h4>
</div>
<div class="container">
  <form id='ticketForm' class="" action="{% url 'tickets:create' %}" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" value="Submit" class='btn btn-primary btn-lg'>

  </form>
</div>

{% endblock %}

bugtracker2/tickets/templates/tickets/ticket_list.html
{% extends "tickets/ticket_base.html" %}
{% block pre_ticket_content %}
<div class="col-md-4">
  {% if request.user.is_authenticated %}
    <div class="card card-with-shadow">
      <div class="content">
        <h5 class='title'>Your Projects</h5>
        <ul class='list-unstyled'>
          {% for member_project in get_user_projects  %}
          <li class='project li-with-bullet'>
             <a href="{% url 'project:single' slug=member_project.project.slug}">
             </a>
           </li>

          {% endfor %}

        </ul>

      </div>

    </div>

  {% endif %}
  <div class="card card-with-shadow">
    <div class="content">
      <h5 class='title'>All PROJECTS</h5>
      <ul class='list-unstyled'>
        {% for other_project in get_other_projects  %}
          <li class='project li-with-bullet'>
              <a href="{% url 'projects:signle' slug=other_project.slug %}"></a>
          </li>
        {% endfor %}
      </ul>

    </div>

  </div>
</div>

{% endblock %}


{% block ticket_content %}
  <div class="col-md-8">
    {% for ticket in ticket_list  %}
    {% include "tickets/_ticket.html" %}

    {% endfor %}

  </div>
{% endblock %}

bugtracker2/tickets/templates/tickets/user_ticket_list.html
{% extends "tickets/ticket_base.html" %}
{% block preticket %}
  <div class="col-md-4">
    <h1>@{{ticket_user.username}}</h1>
  </div>
{% endblock %}
{% block ticket_content %}
  <div class="col-md-8">
    {% if messages %}
        {% for message in messages %}
        <p{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p>
        {% endfor %}
    {% endif %}
    {% for ticket in  ticket_list %}
      {% include "tickets/_ticket.html" %}
    {% endfor %}

  </div>
{% endblock %}