bugtracker2/accounts/urls.py
from django.contrib.auth import views as auth_views
from accounts import views
from django.urls import path

app_name = 'accounts'

urlpatterns = [
    path('login/',auth_views.LoginView.as_view(template_name='accounts/login.html'),name='login'),
    path('logout/', auth_views.LogoutView.as_view(),name='logout'),
    path('signup/', views.SignUp.as_view(),name='signup'),
]

bugtracker2/bugtracker2/urls.py
from django.contrib import admin
from django.urls import path
from . import views as vbase
from django.conf.urls import include
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('', auth_views.LoginView.as_view(template_name='accounts/login.html'),name='login'),
    path('home/',vbase.HomePage.as_view(), name='home'),
    path('accounts/', include('accounts.urls',namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('test/', vbase.TestPage.as_view(), name='test'),
    path('thanks/', vbase.ThanksPage.as_view(), name='thanks'),
    path('admin/', admin.site.urls),
    path('tickets/', include('tickets.urls',namespace='tickets')),
    path('projects/', include('projects.urls',namespace='projects')),
]

bugtracker2/tickets/urls.py
from django.urls import path
from . import views

app_name = 'tickets'

urlpatterns = [
    path('',views.TicketList.as_view(),name='all'),
    path('new/',views.CreateTicket.as_view(),name='create'),
    path('by/<username>/',views.UserTickets.as_view(),name='for_user'),
    path('by/<username>/<pk>/',views.TicketDetail.as_view(),name='single'),
    path('delete/<pk>/',views.DeleteTicket.as_view(),name='delete'),
]

bugtracker2/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
    <title>Bug Tracker</title>
      <!-- CSS only -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'bugtracker2/css/master.css' %}">
    {% block head %}
    {% endblock %}

  </head>


  <body>

        <nav class="navbar-total navbar navbar-default navbar-expand-lg mynav navbar-light ">
          <a class="navbar-brand mynav mr-auto" href="{% url 'home' %}">Bug Tracker</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
              {% if user.is_authenticated %}
                    <a target="_blank" href="{% url 'admin:index' %}" class="mynav ml-auto btn btn-simple">Admin</a>
                    <a href="{% url 'tickets:create' %}" class="mynav btn btn-simple">New Ticket</a>
                    <a href="{% url 'projects:all' %}" class="mynav btn btn-simple">Projects</a>
                    <a href="{% url 'projects:create' %}" class="mynav btn btn-simple">New Project</a>
                    <a href="{% url 'accounts:logout' %}" class="mynav btn btn-simple">Log out</a>
              {% else %}
                    <a href="{% url 'projects:all' %}"class="mynav ml-auto btn btn-simple">Projects</a>
                    <a href="{% url 'accounts:login' %}" class="mynav btn btn-simple">Log in</a>
                    <a href="{% url 'accounts:signup' %}" class="mynav btn btn-simple">Sign up</a>
              {% endif %}

          </div>
        </nav>
<p></p>
        <div class="container mycontent">
          {% block content %}

          {% endblock %}

        </div>



<canvas id="canvas"></canvas>


<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
  <script src="{% static "bugtracker2/js/master.js" %}" type="text/javascript" ></script>
</html>

bugtracker2/templates/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Welcome to the Bug Tracker Home!</h1>

{% endblock %}

bugtracker2/templates/test.html
{% extends "base.html" %}
{% block content %}

  <div class="container">
    <h1>You are now logged in!</h1>
  </div>

{% endblock %}

bugtracker2/templates/thanks.html
{% extends "base.html" %}
{% block content %}

  <h1>Thanks for visiting! Come back soon!</h1>
  
{% endblock %}