bugtracker2/bugtracker2/urls.py
from django.contrib import admin
from django.urls import path
from . import views as vbase
from django.conf.urls import include
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('', auth_views.LoginView.as_view(template_name='accounts/login.html'),name='login'),
    path('home/',vbase.HomePage.as_view(), name='home'),
    path('accounts/', include('accounts.urls',namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('test/', vbase.TestPage.as_view(), name='test'),
    path('thanks/', vbase.ThanksPage.as_view(), name='thanks'),
    path('admin/', admin.site.urls),
    path('tickets/', include('tickets.urls',namespace='tickets')),
    path('projects/', include('projects.urls',namespace='projects')),
]

bugtracker2/projects/urls.py
from django.urls import path
from . import views

app_name = 'projects'

urlpatterns = [
    path('',views.ListProject.as_view(),name='all'),
    path('new/', views.CreateProject.as_view(), name='create'),
    path('ticket/in/<slug>/', views.SingleProject.as_view(),name='single'),
    path('join/<slug>/', views.JoinProject.as_view(),name='join'),
    path('leave/<slug>/', views.LeaveProject.as_view(),name='leave'),
]

bugtracker2/tickets/urls.py
from django.urls import path
from . import views

app_name = 'tickets'

urlpatterns = [
    path('',views.TicketList.as_view(),name='all'),
    path('new/',views.CreateTicket.as_view(),name='create'),
    path('by/<username>/',views.UserTickets.as_view(),name='for_user'),
    path('by/<username>/<pk>/',views.TicketDetail.as_view(),name='single'),
    path('delete/<pk>/',views.DeleteTicket.as_view(),name='delete'),
]

bugtracker2/projects/models.py
from django.db import models
from django.utils.text import slugify
import misaka
from django.urls import reverse

from django.contrib.auth import get_user_model
User = get_user_model()

from django import template
register = template.Library()

class Project(models.Model):
    name = models.CharField(max_length=255, unique=True)
    slug = models.SlugField(allow_unicode=True, unique=True)
    description = models.TextField(blank=True, default='')
    description_html = models.TextField(editable=False, default='',blank=True)
    members = models.ManyToManyField(User,through='ProjectMember')

    def __str__(self):
        return self.name

    def save(self,*args,**kwargs):
        self.slug = slugify(self.name)
        self.description_html = misaka.html(self.description)
        super().save(*args,**kwargs)

    def get_absolute_url(self):
        return reverse('projects:single',kwargs={'slug':self.slug})

    class Meta:
        ordering = ['name']

class ProjectMember(models.Model):
    project = models.ForeignKey(Project,related_name='memberships', on_delete=models.CASCADE)
    user = models.ForeignKey(User, related_name='user_projects', on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

    class Meta:
        unique_together = ('project','user')

bugtracker2/projects/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from django.urls import reverse
from django.views import generic
from django.shortcuts import get_object_or_404, redirect
from django.contrib import messages
from . import models
from django.db import IntegrityError
from projects.models import Project,ProjectMember
from django.http import HttpResponse, HttpResponseRedirect


# Create your views here.
class CreateProject(LoginRequiredMixin,UserPassesTestMixin,generic.CreateView):
    def test_func(self):
        return self.request.user.is_staff
    def handle_no_permission(self):
        messages.add_message(self.request, messages.INFO, 'Not enough permissions to create a project')
        return HttpResponseRedirect(self.request.META.get('HTTP_REFERER'))

    fields = ('name','description')
    model = Project

class SingleProject(generic.DetailView):
    model = Project

class ListProject(generic.ListView):
    model = Project

class JoinProject(LoginRequiredMixin,UserPassesTestMixin, generic.RedirectView):
    def test_func(self):
        return self.request.user.is_staff

    def handle_no_permission(self):
        messages.add_message(self.request, messages.INFO, 'Not enough permissions to join a project')
        return HttpResponseRedirect(self.request.META.get('HTTP_REFERER'))

    def get_redirect_url(self, *args, **kwargs):
        return reverse("projects:single",kwargs={"slug": self.kwargs.get("slug")})

    def get(self, request, *args, **kwargs):
        project = get_object_or_404(Project,slug=self.kwargs.get("slug"))

        try:
            ProjectMember.objects.create(user=self.request.user,project=project)

        except IntegrityError:
            messages.warning(self.request,("Warning, already a member of {}".format(project.name)))

        else:
            messages.success(self.request,"You are now a member of the {} project.".format(project.name))

        return super().get(request, *args, **kwargs)


class LeaveProject(LoginRequiredMixin, generic.RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        return reverse("projects:single",kwargs={"slug": self.kwargs.get("slug")})

    def get(self, request, *args, **kwargs):

        try:

            membership = models.ProjectMember.objects.filter(
                user=self.request.user,
                project__slug=self.kwargs.get("slug")
            ).get()

        except models.ProjectMember.DoesNotExist:
            messages.warning(
                self.request,
                "You can't leave this project because you aren't in it."
            )
        else:
            membership.delete()
            messages.success(
                self.request,
                "You have successfully left this project."
            )
        return super().get(request, *args, **kwargs)

bugtracker2/projects/templates/projects/project_base.html
{% extends "base.html" %}
{% block content %}

  <div class="container">

    <div class="row">
      
      {% block preproject %}{% endblock %}
      {% block project_content %}{% endblock %}
      {% block postproject %}{% endblock %}
    </div>

  </div>

{% endblock %}

bugtracker2/projects/templates/projects/project_detail.html
{% extends "projects/project_base.html" %}
{% block preproject %}

  <div class="container">

    <h1>{{project.name}}</h1>
    <h2> Member Count: {{project.members.count}}</h2>

  </div>

  <div class="container projectcontent">

		{% if user in project.members.all %}

			<a href="{% url 'projects:leave' slug=project.slug %}" class="btn btn-lg btn-fill btn-warning"><span class="glyphicon glyphicon-remove-circle"></span> Leave </a>

      {% else %}
      {% if messages %}
        {% for message in messages %}

        <p{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p>

        {% endfor %}
        {% endif %}

			<a href="{% url 'projects:join' slug=project.slug %}" class="btn btn-lg btn-fill btn-warning"><span class="glyphicon glyphicon-ok-circle"></span> Join </a>

    {% endif %}

  </div>

{% endblock %}

{% block project_content %}

  <div class="col-md-12">

      <a href="{% url 'tickets:create' %}?Project={{project.name}}">New Ticket</a>
      <hr>

    	{% if project.tickets.count == 0 %}

    	<h2>No tickets for this project yet!</h2>

      	{% else %}
    		{% for ticket in project.tickets.all %}
    			{% include "tickets/_ticket.html" %}
          <hr>
    		{% endfor %}

    	{% endif %}

    </div>
{% endblock %}

bugtracker2/projects/templates/projects/project_form.html
{% extends "projects/project_base.html" %}
{% load bootstrap3 %}

{% block project_content %}
  <div class="container">

    <h4>Create a new project</h4>

  </div>
  
  <div class="container">

    <form method="POST" action="{% url 'projects:create' %}" id="projectForm">
      {% csrf_token %}
      {% bootstrap_form form %}
      <input type="submit" value="Create" class="btn btn-primary btn-large">
    </form>

  </div>

{% endblock %}

bugtracker2/projects/templates/projects/project_list.html
{% extends "projects/project_base.html" %}
{% block preproject %}

  <div class="col-md-4">
    <div class="content">

      <h2>Projects</h2>
      <p>List of open projects</p>
      {% if user.is_authenticated %}
        <h2>Welcome back</h2>
        <a href="{% url 'tickets:for_user' username=user.username %}">@{{user.username}}</a>
      {% endif %}

    </div>
  </div>

{% endblock %}
{% block project_content %}

  <div class="col-md-8">

    {% if messages %}
      {% for message in messages %}
        <p{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p>
      {% endfor %}
    {% endif %}

    {% if user.is_authenticated %}
      <a href="{% url 'projects:create' %}" class='btn'>Create New Project</a>
    {% endif %}

    <div class="list-group">

      {% for project in object_list %}
        <div class="list-group-item">

          <a href="{% url 'projects:single' slug=project.slug %}"><h3 class='title list-group-item-heading'>{{project.name}}</h3></a>

          <div class="list-group-item-text container-fluid">

            {{project.description_html|safe}}

            <div class="row">

              <div class="col-md-4">
                <span class='badge'>{{project.members.count}} </span>
                member{{project.members.count|pluralize}}
              </div>
              <div class="col-md-4">
                <span class='badge'>{{project.tickets.count}} </span>
                tickets{{project.members.count|pluralize}}
              </div>

              </div>
            </div>
          </div>
      {% endfor %}
        </div>
    </div>

{% endblock %}